package com.app.errors;

public enum ErrorType {
    CANNOT_CLOSE_ALL,
    CANNOT_CLOSE_STATEMENT_ANDOR_CONNECTION,
    CANNOT_CLOSE_RESULT_SET,
    CANNOT_CLOSE_CONNECTION,
    CANNOT_CREATE_CONNECTION,
    CANNOT_GET_DATA_FROM_DATABASE,
    WRONG_LOGIN_ANDOR_PASSWORD,
    CANNOT_CLOSE_PREPARED_STATEMENT_ANDOR_CONNECTION,
    PREPARED_STATEMENT_DOESNT_WORK_PROPERLY,
    NO_CONNECTION_TO_DATABASE,
    ERROR_OF_ERROR,
    CONFIGURATION_FILE_IS_MISSING
}